name: Display GitHub Secrets and Environment Variables

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  display:
    runs-on: ubuntu-latest

    steps:
      - name: Display Environment Variable
        run: |
          echo "Environment Variable VALUE:"
          echo $IP
        env:
          MY_ENV_VARIABLE: ${{ vars.IP }} # Reference your environment variable here

      - name: Display Secret (Redacted in Logs)
        run: |
          echo "Secret VALUE:"
          echo $MY_SECRET
        env:
          MY_SECRET: ${{ secrets.TEST }} # Reference your GitHub secret here

