name: Deploy to B2C

on:
  workflow_dispatch: # Only manual triggering allowed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          host: 3.110.90.168
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22

      # Step 3: Rsync to EC2 instance
      - name: Deploy to B2C Server
        run: |
          rsync -avz --exclude=logs/* ./ ubuntu@3.110.90.168:/home/ubuntu/test/backend
