name: Create File on Remote Server

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (optional if you need code access)
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a file on the remote server
      - name: SSH into the server and create a file
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 3.110.90.168          # Add your remote server IP in GitHub Secrets
          username: ubuntu      # Add your username in GitHub Secrets
          key: ${{ secrets.PRIVATE_KEY }}            # Add your private SSH key in GitHub Secrets
          port: 22                                   # Default SSH port
          script: |
            echo "Hello, this is a test file!" > ~/test.txt
            ls -l ~/test.txt
