name: Deploy Folder to Remote Server

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH key to connect to the remote EC2 instance
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }} # Add your private SSH key as a GitHub Secret
          known-hosts: |
            3.110.90.168

      # Rsync folder to EC2 server
      - name: Deploy folder to EC2 instance
        run: |
          rsync -avz ./ ubuntu@3.110.90.168:/home/ubuntu/test/backend
