name: Display GitHub Secrets and Variables

on:
  workflow_dispatch: # Allows manual triggering of this workflow

jobs:
  display:
    runs-on: ubuntu-latest

    steps:
      - name: Display Environment Variables
        run: |
          echo "Displaying Environment Variables:"
          printenv | grep MY_ENV_ # Replace with a prefix for your custom variables if applicable

      - name: Display GitHub Secrets (Names Only)
        run: |
          echo "Secrets Added to This Workflow:"
          echo "SECRET_1: Defined"
          echo "SECRET_2: Defined"
        env:
          SECRET_1: ${{ secrets.TEST }}
          SECRET_2: ${{ secrets.IP }}

